---
  - name: Install devinfra dependencies
    apt: state=installed pkg={{ item }}
    with_items: "{{ devinfra_required_packages }}"

  - name: Clone cd-ws-infa project
    git:
      repo: 'https://github.com/ollin/cd-ws-infa.git'
      dest: '/home/dev/cd-ws-infa'

  - name: Set permissions to user dev
    file:
      path: '/home/dev/cd-ws-infa'
      recurse: yes
      group: dev
      owner: dev

  - name: Add hosts in /etc/hosts
    lineinfile:
      dest: /etc/hosts
      line: "{{ item }}"
    with_items: "{{ devinfra_hosts }}"

  - name: Runs docker compose
    docker_service:
      state: present
      project_src: "/home/dev/cd-ws-infa"
#    register: output
#
#  - debug: var=output




