---
  - name: Install docker compose dependencies
    apt: state=installed pkg={{ item }}
    with_items: "{{ docker_compose_required_packages }}"

  - name: Installing dependencies
    easy_install:
      name: pip
      state: latest

  - name: Installing docker compose
    pip:
      name: docker-compose
      version: "{{ docker_compose_version if docker_compose_version else omit }}"
      state: present