---
  - name: Update APT package cache
    apt: update_cache=yes cache_valid_time=3600

                  #password="dev123" # created via mkpasswd --method=SHA-512 # see http://docs.ansible.com/ansible/faq.html#how-do-i-generate-crypted-passwords-for-the-user-module
  - user: name=dev password="$6$9UEVStX2$O9dJOSFAfFqKxM8Mlmt8xXn1olSdrvCqZYFwWbJOHzlVzE1VjYczaEDcjfbOCsARstS/n6OG6SVRt4WzcOeiw1" comment="Developer" groups="sudo,adm" shell="/bin/bash"

  - file: path=/home/dev/Desktop state=directory owner=dev group=dev mode="u=rwx,g=rx,o=rx"

  - name: run ansible galaxy
    local_action: command ansible-galaxy install -r requirements.yml --ignore-errors



