version: '2'

volumes:
  jenkins-home:
  gogs-data:
  db-data:
  nexus-data:

networks:
  nautsch.net:

services:
  nginxedge:
    image: jwilder/nginx-proxy
    container_name: nginx-edge
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    networks:
      nautsch.net:
    restart: always

  ci:
    image: jenkins:2.7.2
    container_name: ci
    environment:
      - VIRTUAL_HOST=ci.nautsch.net
      - VIRTUAL_PORT=8080
    volumes:
      - jenkins-home:/var/jenkins_home
    networks:
      nautsch.net:
        aliases:
          - ci.nautsch.net
    restart: always

  git:
    image: gogs/gogs:0.9.71
    container_name: git
    dns_search: .
    ports:
      - "10080:3000"
    environment:
      - VIRTUAL_HOST=git.nautsch.net
      - VIRTUAL_PORT=3000
    volumes:
      - gogs-data:/data
      - ./gogs/data/gogs/conf/app.ini:/data/gogs/conf/app.ini
    domainname: nautsch.net
    links:
      - db
    networks:
      nautsch.net:
        aliases:
          - git.nautsch.net
    restart: always

  db:
    build:
      context: ./db
    container_name: db
    hostname: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_USER=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    networks:
      nautsch.net:
        aliases:
          - db.nautsch.net
    restart: always

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    environment:
      - VIRTUAL_HOST=nexus.nautsch.net
      - VIRTUAL_PORT=8081
    volumes:
      - nexus-data:/nexus-data
    networks:
      nautsch.net:
        aliases:
          - nexus.nautsch.net
    restart: always




